spring.application.name=vydat

# Railway Public PostgreSQL Connection
spring.datasource.url=jdbc:postgresql://yamanote.proxy.rlwy.net:52744/railway?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=pNgiUrhrlsPnHqMprtvVcCiyHxFUuUeD
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate (JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.jpa.open-in-view=false
